# Generated by Django 4.0.3 on 2022-03-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, unique=True)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('anonymity', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('uptime', models.CharField(max_length=255)),
                ('response', models.CharField(max_length=255)),
            ],
        ),
    ]
